<?php

namespace Unit\DZ11;

use App\Http\Services\DZ11\aService;
use App\Http\Services\DZ11\bService;
use PHPUnit\Framework\TestCase;

class bServiceTest extends TestCase
{

    protected bService $bService;
    public static function provideDataForBService(): array
    {
        return [
            [
                [10,5,7,9,55,11,20,21,25,35,40],
                'expected' => 8,
            ],
            [
                [10,16,12],
                'expected' => 0,
            ],
            [
                [],
                'expected' => 0,
            ],

        ];
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->bService = new bService();
    }

    /**
     * @dataProvider provideDataForBService
     */
    public function testBService(array $data, int $expected): void
    {
        $count = $this->bService->count($data);
        $this->assertEquals($count, $expected);
    }
}
