<?php

namespace Tests\Unit\DZ11;

use App\Http\Services\DZ11\dService;
use App\Http\Services\DZ11\Methods\evenNumber;
use App\Http\Services\DZ11\Methods\moreTwentyFive;
use PHPUnit\Framework\MockObject\Exception;
use PHPUnit\Framework\TestCase;

class dServiceTest extends TestCase
{

    protected dService $dService;
    protected evenNumber $evenNumber;
    protected moreTwentyFive $moreTwentyFive;

    /**
     * @throws Exception
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->evenNumber = $this->createMock(evenNumber::class);
        $this->moreTwentyFive = $this->createMock(moreTwentyFive::class);
        $this->dService = new dService($this->evenNumber, $this->moreTwentyFive);
    }

    /**
     * @dataProvider Tests\Unit\DZ11\DataProviders\dataProviderDService::provider()
     */
    public function testBService(array $data, array $result, int $expected): void
    {
        $this->evenNumber
            ->method('getEvenInt')
            ->willReturn($result['getEvenInt']);

        $this->moreTwentyFive
            ->method('getMoreTwentyFiveInt')
            ->with($result["getEvenInt"])
            ->willReturn($result['getMoreTwentyFiveInt']);

        $test = $this->dService->dService($data);
        $this->assertEquals($expected, $test);
    }
}
