<?php

namespace Unit\DZ11;

use App\Http\Services\DZ11\aService;
use App\Http\Services\DZ11\bService;
use App\Http\Services\DZ11\cService;
use App\Http\Services\DZ11\dService;
use PHPUnit\Framework\TestCase;
use Unit\DZ11\provideDataForDService;

class dServiceTest extends TestCase
{

    protected dService $dService;
//    public static function provideDataForDService(): array
//    {
//        return [
//            [
//                [10,5,7,9,55,11,20,21,25,35,40],
//                'expected' => 2,
//            ],
//            [
//                [10,16,12],
//                'expected' => 0,
//            ],
//            [
//                [],
//                'expected' => 0,
//            ],
//
//        ];
//    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->dService = new dService();

    }

    /**
     * @dataProvider Unit\DZ11\provideDataForDService;
     */
    public function testBService(array $data, int $expected): void
    {
        $count = $this->dService->count($data);
        $this->assertEquals($count, $expected);
    }
}
