<?php

namespace Unit\DZ11;

use App\Http\Services\DZ11\cService;
use App\Http\Services\DZ11\Methods\lessTen;
use PHPUnit\Framework\MockObject\Exception;
use PHPUnit\Framework\TestCase;

class сServiceTest extends TestCase
{

    protected cService $cService;
    protected lessTen $lessTen;

    /**
     * @throws Exception
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lessTen = $this->createMock(lessTen::class);
        $this->cService = new cService($this->lessTen);
    }

    /**
     * @dataProvider Tests\Unit\DZ11\DataProviders\dataProviderCService::provider()
     */
    public function testBService(array $data, array $result, int $expected): void
    {
        $this->lessTen
            ->method('getLessTenInt')
            ->willReturn($result);

        $test = $this->cService->cService($data);
        $this->assertEquals($test, $expected);
    }
}
