<?php

namespace Unit\DZ11;

use App\Http\Services\DZ11\aService;
use App\Http\Services\DZ11\bService;
use App\Http\Services\DZ11\cService;
use PHPUnit\Framework\TestCase;

class сServiceTest extends TestCase
{

    protected cService $cService;
    public static function provideDataForCService(): array
    {
        return [
            [
                [10,5,7,9,55,11,20,21,25,35,40],
                'expected' => 3,
            ],
            [
                [10,16,12],
                'expected' => 0,
            ],
            [
                [],
                'expected' => 0,
            ],

        ];
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cService = new cService();
    }

    /**
     * @dataProvider provideDataForCService
     */
    public function testBService(array $data, int $expected): void
    {
        $count = $this->cService->count($data);
        $this->assertEquals($count, $expected);
    }
}
