<?php

namespace Unit\Users\Login;

use App\Http\Services\User\Login\LoginDTO;
use App\Http\Services\User\Login\Handle\CheckValidDataHandle;
use Tests\TestCase;

class CheckValidDataHandleTest extends TestCase
{
    protected CheckValidDataHandle $checkValidDataHandle;

    /**
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->checkValidDataHandle = new CheckValidDataHandle();

    }
    /**
     * @dataProvider Tests\Unit\Users\Login\DataProviders\ProvideDataForCheckValidDataHandle::LoginServiceTest()
     */
    public function testLoginService(array $data, bool $result, bool $expected): void
    {
        $loginDTO = new LoginDTO($data['email'], $data['password']);
        $data = $this->checkValidDataHandle->handle($loginDTO, function (LoginDTO $loginDTO){
            return $loginDTO;
        });
        var_dump($data);
        $this->assertSame($expected,$data instanceof LoginDTO);
    }
}
