<?php

namespace Unit\Users\Login;

use App\Http\Repositories\User\WhiteListIp\SetActivityRepository;
use App\Http\Services\User\Login\Handle\SetLastActivityUserHandle;
use App\Http\Services\User\Login\LoginDTO;
use PHPUnit\Framework\MockObject\Exception;
use Tests\TestCase;

class SetLastActivityTest extends TestCase
{
    protected SetActivityRepository $setActivityRepository;
    protected SetLastActivityUserHandle $activityUserHandle;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setActivityRepository = $this->createMock(SetActivityRepository::class);
        $this->activityUserHandle = new SetLastActivityUserHandle($this->setActivityRepository);


    }
    /**
     * @dataProvider Tests\Unit\Users\Login\DataProviders\ProvideDataForSetLastActivity::LoginServiceTest()
     */
    public function testLoginService(array $data, bool $result, bool $expected): void
    {
        $loginDTO = new LoginDTO($data['email'], $data['password']);
        $loginDTO->setUserId($data['id']);


        $this->setActivityRepository
            ->method('setUserActivity')
            ->willReturn($result);


        $final = $this->activityUserHandle->handle($loginDTO, function (LoginDTO $loginDTO){
            return $loginDTO;
        });
        $this->assertSame($expected, $final instanceof LoginDTO);
    }
}
